## Wifi_localization

In [1]:
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('pdf', 'svg')
%config InlineBackend.figure_format = 'retina'

In [2]:
import numpy as np

Соберём данные в виде: 
\begin{equation*}
X = \begin{bmatrix}
     x^{(1)}_1 & x^{(1)}_2 & ... & x^{(1)}_M \\
     ... \\
     x^{(N)}_1 & x^{(N)}_2 & ... & x^{(N)}_M \\
    \end{bmatrix}, 
    \vec{y} =  \begin{bmatrix} y_1 \\ ... \\ y_N \end{bmatrix}
\end{equation*}
, где $M$ - количество признаков (атрибутов), используемых моделью, а $N$ - количество экземпляров данных.
В нашем случае: M = 7, N = 2000

In [3]:
file = open("wifi_localization.txt")
X = []
Y = []
for file_str in file:
    x = []
    str_spl = file_str.split()
    for i in range(7):
        x.append(int(str_spl[i]))        
    X.append(x)
    Y.append(int(str_spl[7]))

X_titles = np.array(["Сеть №1","Сеть №2","Сеть №3","Сеть №4","Сеть №5","Сеть №6","Сеть №7"]) 
Y_title = np.array(['Комната'])
X = np.array(X)
Y = np.array(Y)
print(X_titles)
print(X[::100])
print(Y_title)
print(Y[::100])
file.close()

['Сеть №1' 'Сеть №2' 'Сеть №3' 'Сеть №4' 'Сеть №5' 'Сеть №6' 'Сеть №7']
[[-64 -56 -61 -66 -71 -82 -81]
 [-72 -59 -65 -75 -81 -84 -91]
 [-58 -54 -52 -61 -74 -75 -82]
 [-61 -57 -63 -67 -72 -77 -82]
 [-60 -54 -56 -64 -70 -78 -80]
 [-42 -53 -62 -38 -66 -65 -69]
 [-19 -60 -56 -36 -63 -70 -75]
 [-38 -56 -56 -37 -62 -67 -67]
 [-42 -55 -56 -43 -73 -76 -75]
 [-41 -54 -59 -41 -60 -76 -74]
 [-48 -54 -50 -49 -61 -81 -84]
 [-51 -55 -54 -49 -60 -79 -84]
 [-51 -54 -53 -55 -66 -77 -85]
 [-52 -60 -51 -46 -63 -84 -77]
 [-51 -55 -46 -54 -63 -84 -79]
 [-58 -56 -47 -62 -36 -85 -84]
 [-63 -54 -53 -65 -52 -92 -89]
 [-61 -54 -45 -66 -45 -88 -87]
 [-61 -52 -48 -57 -47 -85 -85]
 [-61 -49 -42 -66 -43 -80 -91]]
['Комната']
[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]


Можно заметить, что набор данных отсортирован по классу


In [4]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model, metrics

In [5]:
X_train, X_test, Y_train ,Y_test = train_test_split(X,Y)

### Тренировка полной модели (все атрибуты и классы)
Попробуем использовать все семь атрибутов для тренировки модели и новых предсказаний.

In [6]:
log = linear_model.LogisticRegression(solver = 'lbfgs',multi_class='auto',max_iter = 10000)
log.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

Обучаем модель, выводим тестовые данные, данные, которые предсказала модель и точность предсказания.

In [10]:
predict = log.predict(X_test)
print(Y_test)
print(predict)
print("Accuracy:", metrics.accuracy_score(Y_test, predict))
print(log.predict_proba(X_test))

[4 2 1 4 3 4 4 3 4 1 4 4 1 4 3 4 1 4 4 3 4 1 2 3 3 4 1 4 2 2 4 1 1 2 2 4 4
 1 4 4 3 4 1 1 3 4 3 2 1 1 1 3 3 3 3 3 3 4 2 2 3 4 2 2 4 4 1 1 4 2 2 4 4 1
 2 2 1 4 2 2 1 2 2 4 4 4 4 1 1 2 3 3 4 2 3 3 1 3 3 3 2 1 3 4 4 2 3 1 1 3 2
 3 1 4 4 1 1 3 2 2 2 2 3 2 3 1 3 2 3 3 1 2 1 4 1 1 4 3 1 4 4 3 1 1 1 1 2 3
 4 2 1 2 3 4 2 2 3 2 1 1 4 2 1 3 1 3 1 3 2 2 4 4 2 2 2 2 4 3 2 1 2 1 2 1 1
 3 3 3 3 3 3 1 1 4 4 2 3 1 1 4 4 2 2 4 4 2 4 2 1 2 1 3 2 3 4 3 1 3 1 2 4 1
 1 3 1 1 4 1 1 4 1 2 2 2 2 1 4 1 3 2 3 2 2 2 3 4 4 3 4 1 3 4 1 2 2 1 1 2 4
 1 2 4 2 2 2 4 2 4 4 3 4 3 1 2 3 3 4 4 4 4 3 4 1 4 4 4 1 4 3 1 4 2 1 3 4 1
 3 4 1 1 1 4 1 4 1 2 3 2 2 2 1 4 3 4 2 4 4 4 2 2 4 2 1 3 2 1 4 1 4 4 2 2 4
 3 2 3 3 3 2 2 4 3 4 1 4 1 3 1 2 3 3 1 4 4 4 4 4 1 3 4 4 1 2 2 4 1 1 1 3 3
 1 4 4 1 3 3 3 2 4 2 4 1 2 4 4 1 4 4 3 1 2 2 3 2 2 2 2 1 4 3 4 1 4 2 1 1 4
 3 4 1 1 4 3 1 3 2 2 3 4 4 4 2 1 1 2 2 1 4 4 1 3 2 3 3 1 4 3 2 4 1 2 2 4 3
 3 1 1 2 4 4 2 1 3 3 1 4 1 3 4 3 3 4 3 3 2 1 1 1 2 1 3 4 4 4 1 3 1 1 4 4 3
 1 4 3 1 1 4 1 1 1 1 1 4 